scope: postgres
namespace: /db/
name: patroni2

restapi:
  listen: 0.0.0.0:8008
  connect_address: patroni2:8008

zookeeper:
  hosts: ['zookeeper1:2181', 'zookeeper2:2181', 'zookeeper3:2181']

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        wal_keep_segments: 8
        max_wal_senders: 5
        max_replication_slots: 5
        checkpoint_timeout: 30
  initdb:
  - encoding: UTF8
  - data-checksums
  pg_hba:
  - host replication replicator 0.0.0.0/0 md5
  - host all all 0.0.0.0/0 md5
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 0.0.0.0:5432
  connect_address: patroni2:5432
  use_slots: true
  data_dir: /data/patroni
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: "${PATRONI_REPLICATION_USERNAME}"
      password: "${PATRONI_REPLICATION_PASSWORD}"
    superuser:
      username: postgres
      password: "${POSTGRES_PASSWORD}"
  parameters:
    unix_socket_directories: '.'
    wal_keep_size: '2048'
    max_wal_senders: 10
    log_replication_commands: 'on'
    wal_log_hints: 'on'
